# Generated by Django 3.2.2 on 2021-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='AboutUs_images', verbose_name="Картинки 'О нас'")),
            ],
        ),
        migrations.CreateModel(
            name='TeamCodifyLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('img_team', models.ImageField(blank=True, null=True, upload_to='TeamsImg', verbose_name='Картинки команды CodifyLab')),
            ],
        ),
    ]
