# Generated by Django 3.2.2 on 2021-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContanctsCodifyLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=55)),
                ('twitter', models.CharField(max_length=55)),
                ('facebook', models.CharField(max_length=55)),
            ],
        ),
    ]
