# Generated by Django 3.2.2 on 2021-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contanctscodifylab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img_plus', models.ImageField(blank=True, null=True, upload_to='Plus_img', verbose_name='Картинки Plus')),
            ],
        ),
    ]
