# Generated by Django 3.2.2 on 2021-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('img_franchise', models.ImageField(blank=True, null=True, upload_to='Franchise_img', verbose_name='Картинки франишизы')),
            ],
        ),
    ]
